name: album
description: A Flutter app that displays albums from JSONPlaceholder.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  equatable: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true